// Short "what it looks like" blurbs for every class the COCO-SSD model can detect.
export const COCO_DESCRIPTIONS: Record<string, string> = {
  person: "An upright human figure with a head, two arms, and two legs.",
  bicycle: "A two-wheeled frame with pedals, a chain, and a seat.",
  car: "A four-wheeled metal body with windows, headlights, and a roof.",
  motorcycle: "A two-wheeled vehicle with an engine, handlebars, and a seat.",
  airplane: "A long fuselage with wide wings and a tail fin.",
  bus: "A long, boxy vehicle with rows of windows for many passengers.",
  train: "A long line of connected carriages running on rails.",
  truck: "A large vehicle with a cab up front and a cargo bed or box behind.",
  boat: "A hull shaped to float on water, often with a mast or motor.",
  "traffic light": "A vertical box with red, yellow, and green lamps.",
  "fire hydrant": "A short red or yellow post with nozzle caps, usually curbside.",
  "stop sign": "A red octagon with white 'STOP' lettering on a pole.",
  "parking meter": "A slim post with a coin/card slot and a small display.",
  bench: "A long flat seat, often with a backrest, resting on two or more legs.",
  bird: "A small feathered animal with wings, a beak, and two legs.",
  cat: "A small furry animal with pointed ears, whiskers, and a long tail.",
  dog: "A furry four-legged animal with a snout and a wagging tail.",
  horse: "A large four-legged animal with a mane, long face, and hooves.",
  sheep: "A woolly four-legged animal, usually white, with a rounded body.",
  cow: "A large four-legged animal with a broad body and horns or udders.",
  elephant: "A massive gray animal with large ears, a trunk, and tusks.",
  bear: "A large, heavy-bodied furry animal with a short tail and round ears.",
  zebra: "A horse-like animal covered in black-and-white stripes.",
  giraffe: "A tall animal with a very long neck and patchy brown markings.",
  backpack: "A fabric bag with two shoulder straps, worn on the back.",
  umbrella: "A folding canopy on a central pole, used against rain or sun.",
  handbag: "A small bag with handles, carried by hand or over the shoulder.",
  tie: "A narrow strip of fabric knotted at the collar and hanging down.",
  suitcase: "A rigid rectangular case with a handle, used for travel.",
  frisbee: "A flat, round plastic disc thrown by hand.",
  skis: "A pair of long, narrow boards strapped to boots for snow travel.",
  snowboard: "A single wide board ridden sideways down snow.",
  "sports ball": "A round ball used in games, often patterned or seamed.",
  kite: "A light frame covered in fabric, flown on a string in the wind.",
  "baseball bat": "A smooth tapered wooden or metal club.",
  "baseball glove": "A padded leather mitt worn to catch a ball.",
  skateboard: "A flat board on four small wheels.",
  surfboard: "A long, flat board used to ride ocean waves.",
  "tennis racket": "An oval strung frame attached to a long handle.",
  bottle: "A narrow-necked container for liquid, usually with a cap.",
  "wine glass": "A stemmed glass with a rounded bowl for wine.",
  cup: "A small open container with a handle, for drinking.",
  fork: "A handle ending in two or more thin prongs.",
  knife: "A handle attached to a flat, sharp-edged blade.",
  spoon: "A handle ending in a shallow oval bowl.",
  bowl: "A round, open container deeper than a plate.",
  banana: "A long curved yellow fruit with a peel.",
  apple: "A round fruit, typically red or green, with a short stem.",
  sandwich: "Fillings layered between two slices of bread.",
  orange: "A round citrus fruit with a bumpy orange peel.",
  broccoli: "A vegetable with a tight, tree-like green head on a stalk.",
  carrot: "A long, tapered orange root vegetable.",
  "hot dog": "A grilled sausage tucked inside a long bun.",
  pizza: "A flat round dough base topped with sauce, cheese, and toppings.",
  donut: "A round, fried piece of dough with a hole in the middle.",
  cake: "A layered baked dessert, often frosted or decorated.",
  chair: "A single seat with a backrest, usually on four legs.",
  couch: "A long, cushioned seat for two or more people.",
  "potted plant": "Leafy greenery growing out of a decorative pot.",
  bed: "A large flat frame with a mattress, for sleeping.",
  "dining table": "A flat, wide surface on legs, surrounded by chairs.",
  toilet: "A ceramic seated fixture with a bowl and flush tank.",
  tv: "A flat rectangular screen, often mounted or on a stand.",
  laptop: "A hinged computer with a keyboard base and a screen lid.",
  mouse: "A small handheld device with buttons, used to control a cursor.",
  remote: "A small handheld device with buttons for controlling electronics.",
  keyboard: "A flat panel of rows of letter and number keys.",
  "cell phone": "A slim rectangular handheld device with a screen.",
  microwave: "A boxy kitchen appliance with a door and control panel.",
  oven: "A large boxy kitchen appliance with a door, used for baking.",
  toaster: "A small metal box with slots on top for bread.",
  sink: "A basin with a faucet, set into a counter.",
  refrigerator: "A tall, boxy appliance with doors, used to keep food cold.",
  book: "A stack of bound pages between two covers.",
  clock: "A round or square face with hands or digits showing the time.",
  vase: "A tall, narrow container for holding flowers.",
  scissors: "Two pivoting blades joined at a screw, with finger loops.",
  "teddy bear": "A soft stuffed toy shaped like a bear.",
  "hair drier": "A handheld device with a nozzle that blows hot air.",
  toothbrush: "A small handle tipped with short bristles.",
};

export function describeClass(className: string): string {
  return (
    COCO_DESCRIPTIONS[className] ??
    "No visual description on file for this object yet."
  );
}
